/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function BasicBean(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/characters/animationrigging.glb");
  const { actions } = useAnimations(animations, group);
  const [animation, setAnimation] = useState("ArmatureAction");
  
  useEffect(() => {
    actions[animation].reset().fadeIn(0.32).play();
    return () => actions[animation]?.fadeOut(0.32);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[4.543, 0.372, -2.157]} scale={0.061}>
          <mesh
            name="Arm"
            castShadow
            receiveShadow
            geometry={nodes.Arm.geometry}
            material={materials["Material.001"]}
            position={[2.072, 1.537, -0.406]}
            scale={0.534}
          />
          <mesh
            name="Body"
            castShadow
            receiveShadow
            geometry={nodes.Body.geometry}
            material={materials["Material.001"]}
            position={[0.166, 1.535, -0.116]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[2.488, 3.352, 3.352]}
          />
          <mesh
            name="Face"
            castShadow
            receiveShadow
            geometry={nodes.Face.geometry}
            material={nodes.Face.material}
            position={[0.58, 2.452, 1.279]}
            rotation={[-0.626, 0, 0]}
            scale={[0.376, 0.07, 0.268]}
          />
          <mesh
            name="Leg"
            castShadow
            receiveShadow
            geometry={nodes.Leg.geometry}
            material={materials["Material.001"]}
            position={[0.63, -0.829, 0.018]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.534}
          />
          <mesh
            name="Ribbon"
            castShadow
            receiveShadow
            geometry={nodes.Ribbon.geometry}
            material={materials["Material.014"]}
            position={[0.302, 1.797, 1.609]}
            rotation={[-0.154, -0.049, -0.222]}
            scale={0.837}
          />
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone003} />
          <primitive object={nodes.leg0} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/animationrigging.glb");
