/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useNavigate } from "react-router-dom";

export function Bank(props) {
  const { nodes, materials } = useGLTF("/models/Bank.glb");
  const [isHovered, setHovered] = useState(false);
  const naviate = useNavigate();
  const handleHover = () => {
    setHovered(true);
  };
  const handleUnhover = () => {
    setHovered(false);
  };

  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={handleHover}
      onPointerOut={handleUnhover}
      onClick={() => naviate("/studentmain/saving")}
    >
      <group
        position={[0.652, 2.721, -2.992]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        // scale={0.624}
        scale={isHovered ? 0.654 : 0.624} // 호버 시 크기 변경
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_1.geometry}
          material={materials["Material.090"]}
          //   material-color={isHovered ? "red" : materials["Material.090"]} // 호버 시 색상 변경
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_2.geometry}
          material={materials["atap.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_3.geometry}
          material={materials["Material.092"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Bank.glb");
