/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useNavigate } from 'react-router-dom';

export function BiddingPlace(props) {
  const { nodes, materials } = useGLTF("/models/BiddingPlace.glb");
  const [isHovered, setHovered] = useState(false);

  const navigate = useNavigate();

  const handleHover = () => {
    setHovered(true);
  };
  const handleUnhover = () => {
    setHovered(false);
  };
  
  return (
    <group {...props} dispose={null}
      onPointerOver={handleHover} 
      onPointerOut={handleUnhover}
    >
      <group position={[3.159, 2.696, -0.024]} 
      scale={isHovered ? [0.982, 0.284, 0.817] :[0.972, 0.274, 0.807]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials["PlasterShader.001"]}
          onClick={() => navigate('/auctionHouse')}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_2.geometry}
          material={materials.WoodFineShader}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_3.geometry}
          material={materials["Roof.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_4.geometry}
          material={materials["Material.146"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_5.geometry}
          material={materials["Roof.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/BiddingPlace.glb");
