/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function BlackBoard(props) {
  const { nodes, materials } = useGLTF("/models/blackboard.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.998, 1.029, -3.111]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.713, 0.388, 0.388]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials["Material.118"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/blackboard.glb");
